title: Shaden Smith
author: Shaden Smith
email: shaden@cs.umn.edu
description: > # this means to ignore newlines until "baseurl:"
  PhD candidate at U. Minnesota. I do research on high performance computing
  and focus on problems that arise in large scale machine learning.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: shaden_smith
github_username:  ShadenSmith
scholar_url: https://scholar.google.com/citations?user=5FhpV14AAAAJ

# profile_picture: hi.jpg

institute_name: University of Minnesota
institute_url: http://cs.umn.edu/

# Build settings
markdown: kramdown
theme: academic-minima
gems:
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  style: association-for-computing-machinery
  sort_by: year
  order: descending
  bibliography_template: bib
  repository: pub-files


